I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 37, in script call
    call pregunta2
  File "game/pregunta_2.rpy", line 29, in script
    $cabreo + 1
  File "game/pregunta_2.rpy", line 29, in <module>
    $cabreo + 1
NameError: name 'cabreo' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 37, in script call
    call pregunta2
  File "game/pregunta_2.rpy", line 29, in script
    $cabreo + 1
  File "F:\Downloads\renpy-6.99.13-sdk\renpy\ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "F:\Downloads\renpy-6.99.13-sdk\renpy\python.py", line 1764, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/pregunta_2.rpy", line 29, in <module>
    $cabreo + 1
NameError: name 'cabreo' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
NN 1.0
