I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 39, in script call
    call pregunta2
  File "game/script.rpy", line 39, in script call
    call pregunta2
ScriptError: could not find label 'pregunta2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 39, in script call
    call pregunta2
  File "C:\game\renpy-6.99.13-sdk\renpy\ast.py", line 1357, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 39, in script call
    call pregunta2
  File "C:\game\renpy-6.99.13-sdk\renpy\script.py", line 871, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'pregunta2'.

Windows-8-6.2.9200
Ren'Py 6.99.14.3135
NN 1.0
